tap "homebrew/cask-fonts"

brew "diff-so-fancy"
brew "git"
brew "gnu-sed"
brew "gh"
brew "go"
brew "jq"
brew "mas"
brew "nvm"
brew "pyenv"
brew "wget"
brew "wifi-password"

cask "1password-cli"
cask "1password"
cask "arq"
cask "cleanshot"
cask "font-inconsolata"
cask "font-source-code-pro"
cask "git-credential-manager"
cask "iterm2"
cask "orbstack"
cask "spotify"
cask "the-unarchiver"
cask "visual-studio-code"

mas "Slack", id: 803453959
mas "Xcode", id: 497799835
