#!/bin/bash

AWS_PROFILE="default"
AWS_ROLE_SESSION="sudo"

while getopts ":p" opt; do
  case "$opt" in
    p)
      AWS_PROFILE="$2"
      shift 2
      ;;
    *)
      break
      ;;
  esac
done

AWS_ROLE_ARN=$(aws configure --profile "$AWS_PROFILE" get role_arn)

if [[ -z "$AWS_ROLE_ARN" ]]; then
  echo "Role ARN is missing from $AWS_PROFILE profile."
  exit 1
fi

ASSUME_ROLE=$(aws sts assume-role \
  --profile="$AWS_PROFILE" \
  --role-arn="$AWS_ROLE_ARN" \
  --role-session-name="$AWS_ROLE_SESSION")

ACCESS_KEY_ID=$(echo "$ASSUME_ROLE" | jq -r '.Credentials.AccessKeyId')
SECRET_ACCESS_KEY=$(echo "$ASSUME_ROLE" | jq -r '.Credentials.SecretAccessKey')
SESSION_TOKEN=$(echo "$ASSUME_ROLE" | jq -r '.Credentials.SessionToken')

AWS_ACCESS_KEY_ID="$ACCESS_KEY_ID" \
AWS_SECRET_ACCESS_KEY="$SECRET_ACCESS_KEY" \
AWS_SESSION_TOKEN="$SESSION_TOKEN" \
"$@"
